name: CI

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ./.node-version
          cache: "yarn"
      - name: Check Node.js version
        run: node --version
      - uses: actions/cache@v3
        id: npm-cache
        with:
          path: node_modules
          # node version の変更により node_modules が変わる可能性があるためキーに入れる
          key: ${{ runner.os }}-node-${{ hashFiles('**/.node-version') }}-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies
        shell: bash
        run: |
          if [ "${{ steps.npm-cache.outputs.cache-hit }}" = "true" ]; then
            echo "skip yarn install"
          else
            yarn --frozen-lockfile
          fi
      - name: Run Lint
        run: yarn lint

  build-check:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ./.node-version
          cache: "yarn"
      - name: Check Node.js version
        run: node --version
      - uses: actions/cache@v3
        id: npm-cache
        with:
          path: node_modules
          # node version の変更により node_modules が変わる可能性があるためキーに入れる
          key: ${{ runner.os }}-node-${{ hashFiles('**/.node-version') }}-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies
        shell: bash
        run: |
          if [ "${{ steps.npm-cache.outputs.cache-hit }}" = "true" ]; then
            echo "skip yarn install"
          else
            yarn --frozen-lockfile
          fi
      - name: Run Build
        run: yarn build
